vesoft-inc/nebula-python

GetFullGraph.py
examples/StorageClientExample.py
nebula/ngData/data.py
nebula/ngMeta/MetaClient.py
nebula/ngStorage/StorageClient.py
nebula/ngStorage/ngProcessor/ScanEdgeProcessor.py
nebula/ngStorage/ngProcessor/ScanVertexProcessor.py
tests/test_StorageClient.py
tests/test_client.py

Add some thrift wrapper about reading  vertexes, edges and meta information.
test on a 3-node cluster:
192.168.8.16 is meta server ip, 45500 is meta listening port, nba is the space name to read.
run example `python3 GetFullGraph.py 192.168.8.16 45500 nba`
result:
```shell
scaning space nba
ok
tagName:  player
vid:  109
{'name': 'Tiago Splitter', 'age': 34}
vid:  119
{'name': 'Kevin Durant', 'age': 30}
vid:  129
{'name': 'Dwyane Wade', 'age': 37}
vid:  139
{'name': 'Marc Gasol', 'age': 34}
vid:  149
{'name': 'Ben Simmons', 'age': 22}
tagName:  team
vid:  209
{'name': 'Timberwolves'}
vid:  219
{'name': '76ers'}
vid:  229
{'name': 'Heat'}
tagName:  player
vid:  108
{'name': 'Boris Diaw', 'age': 36}
vid:  118
{'name': 'Russell Westbrook', 'age': 30}
vid:  128
...
```

add thrift wrapper for meta and storage

---

README.md
nebula2/gclient/net/__init__.py
tests/test_session.py

This commit introduced a new method ConnectionPool.session_context,
which takes exactly the same arguments as ConnectionPool.get_session.
It's just a context manager for handling connection sessions.
Issue:(#84)
Signed-off-by: Wey Gu <weyl.gu@gmail.com>

Introduce contextmanager for ConnectionPool

---

setup.py

The current value of `long_description` should point to `description`. This PR also read the content from README as `long_description`.
(Check the current value on PyPI page: https://pypi.org/project/nebula2-python/)

Improve the package description and set long_description

---

.github/workflows/run_test.yaml
nebula2/gclient/net/ConnectionPool.py
tests/docker-compose.yaml
tests/test_ssl_connection.py
tests/test_ssl_pool.py

fix ssl pool.
BTW, if user writes an invalid SSL configuration, client cannot `ping` the server, and it would raise RuntimeError.
a little confused.

fix ssl pool

---

.github/workflows/run_test.yaml
tests/docker-compose.yaml

confused me how long could it wait for meta ready

---

.github/workflows/run_test.yaml
nebula2/gclient/net/Connection.py
tests/docker-compose-ssl.yaml
tests/test_parameter.py
tests/test_ssl_connection.py
tests/test_ssl_pool.py

Fix failed tests caused by syntax change in the server side

---

nebula2/data/DataObject.py
nebula2/data/ResultSet.py
tests/test_data_from_server.py
tests/test_data_type.py

Support duration type

---

.github/workflows/deploy_release.yaml
tests/docker-compose-ssl.yaml
tests/docker-compose.yaml

1. Replace image tag with v3
2. Fix deploy action

V3.0.0 release

---

nebula3/sclient/BaseResult.py

close #218
From:
https://github.com/vesoft-inc/nebula-python/blob/800f0f96babac87e7aa004534cc4da2b63ed5922/nebula3/sclient/BaseResult.py#L78
we could see the index was mismatched:
```python
(Pdb) self._row.values
[Value(sVal=b'player112'), Value(sVal=b'player112'), Value(sVal=b'Jonathon Simmons'), Value(iVal=29)]
(Pdb) self._col_names
[b'_vid', b'name', b'age']
```

fix scan vertex index for prop value

---

README.md
example/SessinPoolExample.py
nebula3/Config.py
nebula3/Exception.py
nebula3/gclient/net/Session.py
nebula3/gclient/net/SessionPool.py
tests/test_session_pool.py

The purpose of adding the  `session pool` is to solve the problem caused by improperly using the connection pool. For example, a common case is that the user generates a new session, executes a query, and releases the session in a loop, like:
```
// Wrong usage of the connection pool
for(int i=0; i<100; i++) {
// get new session
// execute query
// release session
}
```
This will cause huge traffic in the meta service and may crash the service.
See `example/SessinPoolExample.py` for a more detailed example.
The usage of the connection pool remains unchanged.
There are some limitations:
1. There **MUST** be an existing `space` in the DB before initializing the session pool.
2. Each session pool is corresponding to a single **USER** and a single **Space**. This is to ensure that the user's …

Add session pool

---

.github/workflows/run_test.yaml
nebula2/gclient/net/ConnectionPool.py
tests/test_pool.py
tests/test_session.py

[DO NOT MERGE] Remove unusable connection if connection Ping() failed

---

nebula2/gclient/net/ConnectionPool.py
tests/docker-compose.yaml
tests/test_pool.py
tests/test_session.py

Address some common issues along with https://github.com/vesoft-inc/nebula-python/pull/247:
1. Refactor code of the connection pool to simplify the implementation and print more user-friendly logs
2. Remove unusable connection if connection Ping() failed
3. Add automated test cases regarding the problem above

[v2.6.1 patch] Refactor connection pool and add more tests

---

example/GraphClientSimpleExample.py
nebula3/gclient/net/Connection.py
nebula3/sclient/net/__init__.py

Address https://github.com/vesoft-inc/nebula/issues/5191
Replace the protocol with header protocol
> using compact protocol still cause nebula3.Exception.IOErrorException: Header transport frame was too large
`protocol = TCompactProtocol.TCompactProtocol(transport)`

Replace the protocol with header protocol

---

example/SessinPoolExample.py

None
Current code will cause this error:
```
PS D:\Git\Playground\nebula-python\example> py SessinPoolExample.py
Traceback (most recent call last):
File "C:\Environment\Python\Python311\Lib\site-packages\nebula3\fbthrift\transport\TSocket.py", line 286, in open
handle.connect(address)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "D:\Git\Playground\nebula-python\example\SessinPoolExample.py", line 27, in <module>
conn.open(ip, port, 1000)
File "C:\Environment\Python\Python311\Lib\site-packages\nebula3\gclient\net\Connection.py", line 52, in open
self.open_SSL(ip, port, timeout, None)
File "C:\Environment\Python\Python311\Lib\site-packages\nebula3\gclient\net\Connection.py", line 89, in open_SSL …
```

fix(SessinPoolExample.py): change port

---

README.md
example/FormatResp.py
nebula3/data/DataObject.py

it now calls as_empty which doesn't exist.
n/a
Previously it could not handle empty properly.
- Removed the as_empty call from the attribute map
- return None when it's empty

fix: ValueWrapper.cast support __EMPTY__ type

---

.github/workflows/pull-request-links.yaml
docs/source/conf.py
docs/source/index.rst

ref: #292
align with https://nebulagraph-python.readthedocs.io/

chore: read the doc slug update

---

nebula3/data/DataObject.py

closes https://github.com/vesoft-inc/nebula-python/issues/300

Make tag param optional for Node properties method

---

nebula3/data/DataObject.py

Sorry for introducing this in #302

hotfix invoking the Node tags method

---

.github/workflows/run_test.yaml
README.md
nebula3/Exception.py
nebula3/gclient/net/Connection.py
nebula3/gclient/net/Session.py
nebula3/gclient/net/SessionPool.py
pdm.lock
pyproject.toml
tests/test_connection.py
tests/test_session.py
tests/test_session_pool.py
tests/test_ssl_connection.py

close: #276
- renew session when E_SESSION_INVALID or E_SESSION_TIMEOUT
- re-execute for E_EXECUTION_ERROR.
CI changed: avoid using pdm install, this was due to since py3.12, future's installation requires setuptools but setuptools was removed and thus it requires explicit installation/dependency on setuptools, while, the setuptools version cannot be resolved in py3.6.2+ actually, so we have to use pip install to mitigate this. (cc @frostming , I replaced pdm install with pip install, ping you to see if elegant way exists?)

feat: renew session for expiration, re-execute when error

---

example/ScanVertexEdgeExample.py
nebula3/sclient/GraphStorageClient.py
nebula3/storage/ttypes.py

support auth for scan

---

nebula3/gclient/net/Connection.py
nebula3/gclient/net/Session.py
nebula3/gclient/net/SessionPool.py
tests/test_connection.py
tests/test_session.py
tests/test_session_pool.py
tests/test_ssl_connection.py

fix: remove new exceptions

---

nebula3/sclient/__init__.py

fix scan if leader change.
original error:
```
part_id 9 has leader change, old leader is HostAddr(
host='192.168.15.7',
port=9779), new leader is HostAddr(
host='192.168.15.6',
port=9779)
Traceback (most recent call last):
File "/home/jingchun.xia/anaconda3/lib/python3.11/site-packages/nebula3/sclient/__init__.py", line 176, in do_scan_job
req.part_id,
^^^^^^^^
AttributeError: 'ScanEdgeRequest' object has no attribute 'part_id'
```

fix leader change

---

nebula3/fbthrift/transport/TSocket.py

- https://github.com/wey-gu/jupyter_nebulagraph/issues/46
- https://github.com/pyodide/pyodide/discussions/4150
- https://github.com/emscripten-core/emscripten/issues/11797
This is a fix on Thrift python, to enable nebula-python being supported on jupyterlite, a wasm env in browser powered by pyodide.
This will enable embedding runnable jupyter/python client runtime of nebulagraph in a browser or inline of docs/tutorials in the future.
This is an equivalent downstream implementation of my [pr on fbthrift](https://github.com/facebook/fbthrift/pull/597). 
Just to inspect the sys platform and when it's on WASM(with Emscripten), just don't lock as it was done for Windows.
This change has to be applied again every time thrift gen was triggered.

feat: support JupyterLite/Emscripten

---

README.md
example/FormatResp.py
example/GraphClientSimpleExample.py
example/GraphVis.py
example/apache_echarts.html
example/data.json
nebula3/data/DataObject.py
nebula3/data/ResultSet.py
nebula3/gclient/net/ConnectionPool.py
nebula3/gclient/net/SessionPool.py
tests/test_data_type.py

implement: https://github.com/vesoft-inc/nebula-python/issues/318, https://github.com/vesoft-inc/nebula-python/issues/324
- Docs polished, straightforwardly getting started
- sugars to better handle ResultSet for Graph Vis/Rendering && as Pandas Dataframe
- Optimized Config, now user could omit them to enable ease of first-time try, fixed SessionPool Config Check bug
easily get node list/ edge list and more information in ANY query as a result.
```python
result = session.execute('GET SUBGRAPH WITH PROP 2 STEPS FROM "player101" YIELD VERTICES AS nodes, EDGES AS relationships;')
v = result.dict_for_vis()
{
'nodes': [
{
'id': 'player100',
'labels': ['player'],
'props': {
'name': 'Tim Duncan', 
'age': '42', 
'id': 'player100'
}
},
{
'id': 'player101',
'labels': ['player'],
'props': {
'age': …
```

feat: ResultSet& ValueWrapper sugars for Graph Visualisation & Data Sci

---

README.md
pdm.lock
pyproject.toml
setup.py

- rebuild outdated lock file, or it'll fail to build
- update version for the next release
- fixed broken colab URL

release 3.8.0

---

nebula3/gclient/net/ConnectionPool.py
nebula3/gclient/net/SessionPool.py
setup.py

In NebulaGraph repo ci test, ping was done before the connection pool's init, this was broken in recent changes.
This change fixed it.
issue 1:
a. connection_pool cannot be ping() without init()
b. dependency issue:
- http2 was added, it relied on httpcore-->anyio-->contextvars(only needed when python < 3.7)
- in setup.py, there were httpx[http2] >= 0.22.0, ensures `httpcore-->anyio` BUT NOT `contextvars`
WHY this issue(a, or b) was not found? It could be due to a dirty cache, see issue 2 hided issue 1.
Action: added this dep handling in setup.py
issue 2:
dirty cache in gh runner in `/home/vesoft/actions-runner/_work/_temp/_github_home/.local`
```bash
docker run --rm -e "HOME=/github/home" -v "/home/vesoft/actions-runner/_work/_temp/_github_home":"/github/home" -it …
```

fix: support conn_pool ping before init | add missing dep in py3.6

---

nebula3/gclient/net/Connection.py
nebula3/gclient/net/ConnectionPool.py
nebula3/gclient/net/Session.py
nebula3/gclient/net/SessionPool.py
nebula3/gclient/net/base.py

In this PR,
- Add a base class named BaseExecutor, to be inherited by Session and Session Pool, which have the same functions execute_*
- fix typing ;
- pdm run fmt ;

Add a base class for functions execute_* 

---

README.md
example/Params.py
nebula3/gclient/net/__init__.py
nebula3/gclient/net/base.py
tests/test_parameter.py

Updatet execute_py 
- Return result as python object List[Dict[str, Any]]
- Raise exceptions

feat: primitive params

---

.github/workflows/run_test.yaml
nebula3/gclient/net/SessionPool.py
pyproject.toml
setup.py

Since NebulaGraph Cloud requires TLS connection

support TLS for session pool

---

nebula3/gclient/net/Connection.py

When authenticate to graphd failed,the status of the connection has not been modified, resulting in the inability to continue using it in the future.I encountered this issue and thinking this commit can fix it.
Modify connection status `is_used` to False

fix connection not release bug

---

nebula3/data/DataObject.py
tests/test_data_type.py

cast_primitive does not working correctly for node/relationship's prop value

fix cast primitive for node/relationship
