vesoft-inc/nebula-python

nebula/AsyncClient.py, nebula/Client.py, nebula/ConnectionPool.py
=> Delete debug log

README.md, examples/StorageClientExample.py, nebula/ngStorage/ngProcessor/ScanEdgeProcessor.py, nebula/ngStorage/ngProcessor/ScanVertexProcessor.py, tests/test_StorageClient.py
=> fix timestamp converte

nebula2/common/ttypes.py, nebula2/data/DataObject.py, nebula2/storage/ttypes.py, tests/test_data_type.py
depends on https://github.com/vesoft-inc/nebula-common/pull/351
=> Add int vid

tests/test_connection.py
=> fix connection test

nebula2/sclient/BaseResult.py
=> remove incorrect type check.

tests/docker-compose.yaml
=> Replace v2-nightly docker image with nightly tag

nebula2/gclient/net/__init__.py
enhance compatible, e.g. 
```
from nebula2.gclient.net import ResultSet
```
=> enhance compatible

nebula2/gclient/net/Session.py, tests/test_data_from_server.py
=> Fix json format

setup.py
=> Update license in the package info

tests/docker-compose.yaml, tests/test_session.py
=> Decrease the heartbeat interval to fix unstable ci case

README.md
=> Update README for v3.0.0 release

example/ScanVertexEdgeExample.py, nebula3/sclient/__init__.py
should update the cursor in part_info, otherwise if would use new ScanCursor()
=> fix scan cursor

nebula3/gclient/net/Connection.py
=> Fix execute_json_with_params

tests/test_connection.py
=> Add test for ipv6 address

docs/how-to-update-interface.md
=> fixed thrift update guide

.github/workflows/run_test.yaml
=> Enable action for release branches

.github/workflows/run_test.yaml, nebula2/gclient/net/ConnectionPool.py, setup.py, tests/test_pool.py, tests/test_session.py
=> Add v2.6.1 pre release

README.md, setup.py, tests/docker-compose-ssl.yaml, tests/docker-compose.yaml, tests/test_session.py
=> fix readme

nebula3/sclient/GraphStorageClient.py
=> Bugfix: sclient.get_space_addrs

nebula3/gclient/net/ConnectionPool.py
=> fix: issue #277, logging is not defined

.github/workflows/run_test.yaml, pdm.lock, pyproject.toml, setup.py
=> add setup.py

README.md
also updated badges with pypi/py-version info
follow-up of https://github.com/vesoft-inc/nebula-python/pull/307
=> doc: add note for python3.6 build from source

example/SessinPoolExample.py, nebula3/Config.py, nebula3/gclient/net/Connection.py, nebula3/gclient/net/ConnectionPool.py, nebula3/gclient/net/SessionPool.py, tests/test_connection.py, tests/test_session_pool.py, tests/test_ssl_connection.py
Reverts vesoft-inc/nebula-python#305
=> Revert "add version selection"

.github/workflows/doxygen.yml, doxygen-config
=> Update nodejs dependent actions

pyproject.toml, setup.py
=> release: 3.5.1

docs/how-to-update-interface.md
thrift docs update
----
📚 Documentation preview 📚: https://nebulagraph-python--341.org.readthedocs.build/en/341/
=> chore: update rpc update docs

.github/workflows/deploy_release.yaml
or it failed on the ci runner env
=> ci: drop docker compose v1

nebula3/gclient/net/ConnectionPool.py
Set up daemon attribute instead of method calling
https://lists.denx.de/pipermail/u-boot/2023-September/531354.html
=> Avoid deprecation warning for setDaemon
